

from validator_base.base_exceptions import ValidatorException


class HaveIbeenPwnedException(ValidatorException):
    pass
